apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: chat-app

# On Local
spec:
  accessModes:      
    - ReadWriteOnce   
  capacity:
    storage: 5Gi
  hostPath:
    path: /data
  